version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "${MQ_HTTP_PORT:-15672}:15672"
      - "${MQ_PORT:-5672}:5672"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - mutagen-backend

networks:
  mutagen-backend:
    external: true
    name: mutagen-backend